# Generated by Django 3.2.12 on 2025-05-27 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=50)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocrtesting.class')),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('script_id', models.AutoField(primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocrtesting.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocrtesting.subject')),
            ],
        ),
        migrations.CreateModel(
            name='OCRData',
            fields=[
                ('ocr_id', models.AutoField(primary_key=True, serialize=False)),
                ('page_number', models.IntegerField()),
                ('ocr_json', models.JSONField()),
                ('structured_json', models.JSONField()),
                ('key_json', models.JSONField()),
                ('context', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocrtesting.script')),
            ],
        ),
    ]
