# Generated by Django 5.1.9 on 2025-05-27 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocrtesting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="class_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="ocrtesting.class",
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="class_name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="ocrdata",
            name="script",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ocr_data",
                to="ocrtesting.script",
            ),
        ),
        migrations.AlterField(
            model_name="script",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scripts",
                to="ocrtesting.student",
            ),
        ),
        migrations.AlterField(
            model_name="script",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scripts",
                to="ocrtesting.subject",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="class_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="ocrtesting.class",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ocrdata",
            unique_together={("script", "page_number")},
        ),
        migrations.AlterUniqueTogether(
            name="script",
            unique_together={("student", "subject")},
        ),
        migrations.AlterUniqueTogether(
            name="student",
            unique_together={("roll_number", "class_id")},
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together={("subject_name", "class_id")},
        ),
    ]
