# Generated by Django 5.1.9 on 2025-05-28 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocrtesting", "0002_subject_class_id_alter_class_class_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ocrdata",
            name="key_json",
        ),
        migrations.AlterField(
            model_name="subject",
            name="class_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="ocrtesting.class",
            ),
        ),
        migrations.CreateModel(
            name="KeyOCR",
            fields=[
                ("key_ocr_id", models.AutoField(primary_key=True, serialize=False)),
                ("key_json", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="key_ocr",
                        to="ocrtesting.subject",
                    ),
                ),
            ],
        ),
    ]
