# Generated by Django 5.1.9 on 2025-05-28 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocrtesting", "0003_remove_ocrdata_key_json_alter_subject_class_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="script",
            name="class_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scripts",
                to="ocrtesting.class",
            ),
        ),
    ]
