# Generated by Django 5.1.9 on 2025-05-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocrtesting", "0004_script_class_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="keyocr",
            name="context",
            field=models.TextField(blank=True, null=True),
        ),
    ]
