# Generated by Django 5.1.9 on 2025-05-30 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocrtesting", "0005_keyocr_context"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScriptImage",
            fields=[
                ("image_id", models.AutoField(primary_key=True, serialize=False)),
                ("page_number", models.IntegerField()),
                ("image_data", models.TextField()),
                ("image_filename", models.CharField(max_length=255)),
                ("image_path", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "script",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="ocrtesting.script",
                    ),
                ),
            ],
            options={
                "ordering": ["script", "page_number"],
                "unique_together": {("script", "page_number")},
            },
        ),
    ]
