# Generated by Django 5.1.9 on 2025-05-30 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocrtesting", "0006_scriptimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextractOCR",
            fields=[
                (
                    "textract_ocr_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("page_number", models.IntegerField()),
                ("extracted_text_json", models.JSONField()),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "script",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="textract_ocr_data",
                        to="ocrtesting.script",
                    ),
                ),
            ],
            options={
                "ordering": ["script", "page_number"],
                "unique_together": {("script", "page_number")},
            },
        ),
    ]
