# Generated by Django 5.1.9 on 2025-06-05 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocrtesting", "0007_textractocr"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompareText",
            fields=[
                (
                    "compare_text_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("flagged_text_json", models.JSONField()),
                ("corrected_text_json", models.JSONField()),
                ("final_corrected_json", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "script",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compare_texts",
                        to="ocrtesting.script",
                    ),
                ),
            ],
        ),
    ]
