# Generated by Django 5.1.9 on 2025-06-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocrtesting", "0008_comparetext"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comparetext",
            name="corrected_text_json",
        ),
        migrations.RemoveField(
            model_name="comparetext",
            name="final_corrected_json",
        ),
        migrations.RemoveField(
            model_name="comparetext",
            name="flagged_text_json",
        ),
        migrations.AddField(
            model_name="comparetext",
            name="corrected_text",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="comparetext",
            name="final_corrected_text",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="comparetext",
            name="flagged_text",
            field=models.TextField(default=""),
        ),
    ]
