# Generated by Django 5.1.9 on 2025-06-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocrtesting", "0009_remove_comparetext_corrected_text_json_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comparetext",
            name="corrected_text",
        ),
        migrations.RemoveField(
            model_name="comparetext",
            name="flagged_text",
        ),
        migrations.AddField(
            model_name="comparetext",
            name="restructured",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="comparetext",
            name="vlmdesc",
            field=models.JSONField(default=dict),
        ),
    ]
