# Generated by Django 5.1.9 on 2025-06-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocrtesting", "0010_remove_comparetext_corrected_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="keyocr",
            name="rubrics",
            field=models.TextField(blank=True, null=True),
        ),
    ]
